agent1.sources = r1
agent1.channels = c1
agent1.sinks = k1

# SOURCE: tail file written by Python
agent1.sources.r1.type = exec
agent1.sources.r1.command = tail -F /home/bigdata/usecase/weather.json
agent1.sources.r1.shell = /bin/bash -c

# CHANNEL
agent1.channels.c1.type = memory
agent1.channels.c1.capacity = 10000
agent1.channels.c1.transactionCapacity = 1000

# SINK → KAFKA
agent1.sinks.k1.type = org.apache.flume.sink.kafka.KafkaSink
agent1.sinks.k1.topic = myweather
agent1.sinks.k1.brokerList = localhost:9092,localhost:2093
agent1.sinks.k1.requiredAcks = 1
agent1.sinks.k1.batchSize = 20

# Bind
agent1.sources.r1.channels = c1
agent1.sinks.k1.channel = c1