agent2.sources = r1
agent2.channels = c1
agent2.sinks = h1

# SOURCE: Kafka
agent2.sources.r1.type = org.apache.flume.source.kafka.KafkaSource
agent2.sources.r1.kafka.bootstrap.servers = localhost:9092,localhost:2093
agent2.sources.r1.kafka.topics = myweather
agent2.sources.r1.groupId = flume-hdfs-group

# CHANNEL
agent2.channels.c1.type = file
agent2.channels.c1.checkpointDir = /tmp/flume/checkpoint
agent2.channels.c1.dataDirs = /tmp/flume/data

# SINK → HDFS
agent2.sinks.h1.type = hdfs
agent2.sinks.h1.hdfs.path = /weather/data/
agent2.sinks.h1.hdfs.fileType = DataStream
agent2.sinks.h1.hdfs.writeFormat = Text
agent2.sinks.h1.hdfs.batchSize = 50
agent2.sinks.h1.hdfs.rollInterval = 60

# Bind
agent2.sources.r1.channels = c1
agent2.sinks.h1.channel = c1